### ISSUE TITLE
[FEATURE] Dropdown navbar

### ISSUE THREAD

**Issue by 0xk4b1r** [CryptoverseWeb3/Community.CryptoverseWeb3#10]
Task is to add dropdown navbar 

![image](https://user-images.githubusercontent.com/44284877/192972057-eb8f216d-e307-4b39-869a-4a7246805a43.png)
- remove the times:
 - courses
 - services
 
- add resources nav-item

Resources nav-item should be drop-down nav-item
![image](https://user-images.githubusercontent.com/44284877/192971967-a6c32ae7-4d5b-4b7c-8cd1-1d31630c86df.png)

**Comment by ShorunTech** [comment]
I would love to work on this navbar drop-down

**Comment by 0xk4b1r** [comment]
> I would love to work on this navbar drop-down

Great:
Would you like to check this repo first
https://github.com/cryptoverseWeb3/git-github-practice + you will get more green squares 😄

**Comment by ShorunTech** [comment]
Thank you for this, I just added my name.

**Comment by 0xk4b1r** [comment]
> Thank you for this, I just added my name.

Nice, I have assigned the issue to you.

**Comment by ghost** [comment]
Hey @kabir0x23 , could I contribute in this issue..?

**Comment by 0xk4b1r** [comment]
> Hey @kabir0x23 , could I contribute to this issue..?

This issue already has been assigned to @ShorunTech

you can check out other issues on these repos.
- https://github.com/kabir0x23
- https://github.com/thecyberworld
- https://github.com/CryptoverseWeb3/

**Comment by 0xk4b1r** [comment]
Hello @ShorunTech 
Any progress?
so you are working on this issue,. right?

**Comment by ShorunTech** [comment]
Yes working on it.

**Comment by 0xk4b1r** [comment]
> Yes working on it.

Okay, amazing 😄

**Comment by ShorunTech** [comment]
Have Commit it already



![Screenshot (150)](https://user-images.githubusercontent.com/61280687/193534187-f6bcb96f-b295-4527-8bd8-2cd2eff7a82a.png)

**Comment by 0xk4b1r** [comment]
> Have Commit it already
> 
> ![Screenshot (150)](https://user-images.githubusercontent.com/61280687/193534187-f6bcb96f-b295-4527-8bd8-2cd2eff7a82a.png)

Nice
can you send the Pull Request?

**Comment by ShorunTech** [comment]
Ok, I will do that right away.

**Comment by ShorunTech** [comment]
Can any Maintenance look into this pls, Never See any changes since I make the PR.
