### ISSUE TITLE
[FEATURE] add README.md

### ISSUE THREAD

**Issue by ShorunTech** [CryptoverseWeb3/Community.CryptoverseWeb3#11]
### Detailed description

For new contributors that would like to add one more ideas to this web app need a readme document for guide to run the app locally on there machine. I was able to run the web-app on locally  base on my knowledge about open source.

![Screenshot (136)](https://user-images.githubusercontent.com/61280687/193030231-658f73b7-7e3b-4a3c-8038-bf7857283a11.png)

### Context

- Easy to run the web app locally
- As Guide for improvement
- Gives other to contribute to the project

### Possible implementation

If Permission Granted I can provide a ReadMe Document for the web app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xk4b1r** [comment]
Thanks for creating this issue,

- this project was under development before
- so now, anyone can create PRs for this project

you can take an example from this repository 
https://github.com/thecyberworld/thecyberhub.org

**Comment by issa-me-sush** [comment]
hey! I would love to work on this , could I please be assigned  this issue, if someone isnt already working on it ? :D
