### ISSUE TITLE
[FEATURE] Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by 0xk4b1r** [CryptoverseWeb3/Community.CryptoverseWeb3#12]
### Detailed description

CONTRIBUTING.md file help beginners and contributors understand the structure of the project.

### Possible implementation

use this as an example: (both projects are having the same structure):
- https://github.com/thecyberworld/thecyberhub.org/blob/main/CONTRIBUTING.md

### Additional information

If you need any help let us know.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clairecharles** [comment]
Hey @kabir0x23 can i work on this?

**Comment by 0xk4b1r** [comment]
> Hey @kabir0x23 can i work on this?

Yeah sure,

Will you checkout this repository frist?
> https://github.com/CryptoverseWeb3/git-github-practice
> 
> + You will get more green squares
