### ISSUE TITLE
[FEATURE] Add README.md

### ISSUE THREAD

**Issue by ShorunTech** [CryptoverseWeb3/Community.CryptoverseWeb3#15]
### Detailed description

![Screenshot (148)](https://user-images.githubusercontent.com/61280687/193426413-4ae4e3ad-5605-4701-8e1f-5fade49f753c.png)

### Context

-- Make it Easy for me to run the Website
--Run it Locally
--Easy for new contributors to navigate on the website

### Possible implementation

you can take an example from this repository
https://github.com/thecyberworld/thecyberhub.org

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShorunTech** [comment]
Can this issue be assign to me

**Comment by 0xk4b1r** [comment]
duplicate of #11

**Comment by 0xk4b1r** [comment]
@ShorunTech

**Comment by ShorunTech** [comment]
Ok

**Comment by 0xk4b1r** [comment]
> Ok

you can do this from here
https://github.com/thecyberworld/thecyberhub.org
same reademe file 
just change the name

**Comment by ShorunTech** [comment]
Thank you for that.
