### ISSUE TITLE
[FEATURE] Get started button does not stand out

### ISSUE THREAD

**Issue by Jonniie** [CryptoverseWeb3/Community.CryptoverseWeb3#16]
### Detailed description

The get started button being the primary button should catch a visitor's attention as he visits the page, but currently it kindof blends into the background 

### Context

The get started button should be shown as a primary button which it is

### Possible implementation

Have a more border with more saturated color (if you wouldn't like it to have a background)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xk4b1r** [comment]
> ### Detailed description
> 
> The get started button being the primary button should catch a visitor's attention as he visits the page, but currently it kindof blends into the background
> ### Context
> 
> The get started button should be shown as a primary button which it is
> ### Possible implementation
> 
> Have a more border with more saturated color (if you wouldn't like it to have a background)
> ### Additional information
> 
> _No response_
> ### Code of Conduct
> 
>     * [x]  I agree to follow this project's Code of Conduct

Yes, we have to remove these buttons and have to add something new after the website got completed

**Comment by 0xk4b1r** [comment]
If you have any idea let us know

**Comment by Jonniie** [comment]
Yeah, just a button with more prominent borders or background colour should work fine

**Comment by Jonniie** [comment]
Can I go ahead to work on this?

**Comment by 0xk4b1r** [comment]
> Can I go ahead to work on this?

Yes, i am assigning you this issue

**Comment by Jonniie** [comment]
@kabir0x23 kindly review this 🤗
