### ISSUE TITLE
[BUG] join button not linking to anywhere

### ISSUE THREAD

**Issue by ShorunTech** [CryptoverseWeb3/Community.CryptoverseWeb3#18]
### Detailed description

provide the discord link to join the community, once is been click direct user to discord account. 

### Context

-- it helps any user visiting the site to join the community
-- to get more information
-- create intro to web3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShorunTech** [comment]
Can this issue be assign to me to work on.

**Comment by 0xk4b1r** [comment]
assigned 😄

**Comment by ShorunTech** [comment]
done with the issue raised, the join button now link to discord community.
