### ISSUE TITLE
[FEATURE] add Events page

### ISSUE THREAD

**Issue by 0xk4b1r** [CryptoverseWeb3/Community.CryptoverseWeb3#30]
### Detailed description

Add a Events section to the site
Can be made using React + styled-components.
- Add dummy data after completing this page, we will add backend later on.
### Context

Events plays important role in learning

### Possible implementation

Example: 👇
- You can make this type UI under the Events section.
- https://www.thecyberhub.org/events

![image](https://user-images.githubusercontent.com/44284877/195826017-738eb2cc-444d-4a0e-8738-693981f44b84.png)

### Additional information

source code: https://github.com/thecyberworld/thecyberhub.org

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nijek** [comment]
I would like to do this, can you assign me?
