### ISSUE TITLE
[FEATURE] Jobs/Internships page

### ISSUE THREAD

**Issue by 0xk4b1r** [CryptoverseWeb3/Community.CryptoverseWeb3#32]
### Detailed description

For example, what we trying to build:

<img src="https://user-images.githubusercontent.com/44284877/193441392-ea8f3663-e779-492c-b89e-53d627d7f144.png" alt="drawing" width="350"/>

our website link: 
https://www.thecyberhub.org/prep/jobs
http://localhost:3000/prep/jobs

### Context

The jobs page will going to help community members and other users 

### Possible implementation

tech-stack: react and styled-components or CSS

### Additional information

If you need any help or have any doubts, let us know.

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nijek** [comment]
I would like to do this, can you assign me?

**Comment by 0xk4b1r** [comment]
> I would like to do this, can you assign me?

Sure
