### ISSUE TITLE
 [FEATURE] Create a page to showcase our open-source projects

### ISSUE THREAD

**Issue by 0xk4b1r** [CryptoverseWeb3/Community.CryptoverseWeb3#33]
### Detailed description

Create a page to showcase our open-source projects

open-source projects list:
https://github.com/CryptoverseWeb3

### Context
example: https://www.thecyberhub.org/projects
sourcecode: https://github.com/thecyberworld/thecyberhub.org

### Additional information

If you need any help or have any doubts or questions let us know.

Thank you 😄.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MISSIC17** [comment]
I can do it, how much time would I have to complete it?

**Comment by 0xk4b1r** [comment]
> I can do it, how much time would I have to complete it?

Hey, how much time do you need?

source code is already given from our different websites.

**Comment by MISSIC17** [comment]
About 1/2 days will be enough

**Comment by 0xk4b1r** [comment]
Awesome Assigned to you.

**Comment by MISSIC17** [comment]
Is this supposed to be a single page website or only a page in a bigger website? The example you have sent doesn't seem to be a single page website

**Comment by 0xk4b1r** [comment]
> Is this supposed to be a single page website or only a page in a bigger website? The example you have sent doesn't seem to be a single page website

Yes no longer single page website.

**Comment by MISSIC17** [comment]
ah got it, so I should add projects option in the navbar and make the page right?

**Comment by 0xk4b1r** [comment]
> ah got it, so I should add projects option in the navbar and make the page right?

yes, correct 👍

**Comment by MISSIC17** [comment]
hey! looking at your website wouldn't it be better if I add the projects section in the same main page? Even the navbar component is using a map function to create navLinks which have smooth internal links.

**Comment by 0xk4b1r** [comment]
> hey! looking at your website wouldn't it be better if I add the projects section in the same main page? Even the navbar component is using a map function to create navLinks which have smooth internal links.

Okay, go for it.
