### ISSUE TITLE
[FEATURE] Create About section

### ISSUE THREAD

**Issue by 0xk4b1r** [CryptoverseWeb3/Community.CryptoverseWeb3#34]
### Detailed description

If you click on the About Tab you will only see About without fully details.
but there is About Section on the page, is just to link the About tab to the section on page.

### Context

-- Give new visitor a brief of what the website is all about
-- click on the About Tab to link to the section
-- Help others to easily navigate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by theobiabo** [comment]
I can work on this

**Comment by 0xk4b1r** [comment]
Sure, i am assigning this issue to you.

**Comment by theobiabo** [comment]
Thanks

**Comment by tanyaa-arora** [comment]
hi @kabir0x23 . I'd like to work on this issue. Can you assign it to me?

**Comment by 0xk4b1r** [comment]
> hi @kabir0x23 . I'd like to work on this issue. Can you assign it to me?

Hi @tanyaa-arora 
this issue has already been assigned to @yhoungdev 

you can work on #31 this issue

Thank you
